package com.simplilearn.ph2.beans;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "V_SUBJECT_CLASS")
public class SubjectClass implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "SubjectId")
	private int subjectId; // this will play a role of primary key, generated by hibernate

	@Id
	@Column(name = "ClassId")
	private int classId;

	public SubjectClass() {
	}

	public SubjectClass(int subjectId, int classId) {
		this.subjectId = subjectId;
	}

	public int getSubjectId() {
		return subjectId;
	}

	public void setSubjectId(int subjectId) {
		this.subjectId = subjectId;
	}

	public int getClassId() {
		return classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	@Override
	public String toString() {
		return "SubjectClass [subjectId=" + subjectId + ", classId=" + classId + "]";
	}
}
