package com.simplilearn.ph2.beans;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "V_TEACHER")
public class Teacher {
	@Id
	@Column(name = "TeacherId")
	private int teacherId; // this will play a role of primary key, generated by hibernate

	@Column(name = "TeacherName")
	private String teacherName;

	public Teacher() {
	}

	public Teacher(String teacherName) {
		this.teacherName = teacherName;
	}

	public int getTeacherId() {
		return teacherId;
	}

	public void setTeacherId(int teacherId) {
		this.teacherId = teacherId;
	}

	public String getTeacherName() {
		return teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	@Override
	public String toString() {
		return "Teacher [teacherId=" + teacherId + ", teacherName=" + teacherName + "]";
	}
}
