package com.simplilearn.ph2.beans;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "V_TEACHER_CLASS")
public class TeacherClass implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "TeacherId")
	private int teacherId; // this will play a role of primary key, generated by hibernate

	@Id
	@Column(name = "ClassId")
	private int classId;

	public TeacherClass() {
	}

	public TeacherClass(int teacherId, int classId) {
		this.teacherId = teacherId;
	}

	public int getTeacherId() {
		return teacherId;
	}

	public void setTeacherId(int teacherId) {
		this.teacherId = teacherId;
	}

	public int getClassId() {
		return classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	@Override
	public String toString() {
		return "TeacherClass [teacherId=" + teacherId + ", classId=" + classId + "]";
	}
}
