package com.simplilearn.ph2.beans;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "V_CLASS")
public class V_Class {
	@Id
	@Column(name = "ClassId")
	private int classId; // this will play a role of primary key, generated by hibernate

	@Column(name = "ClassName")
	private String className;

	@OneToMany(cascade = CascadeType.ALL)
	@JoinColumn(name = "ClassId")
	List<Student> students;

	public V_Class() {
	}

	public V_Class(String className) {
		this.className = className;
	}

	public List<Student> getStudents() {
		return students;
	}

	public void setStudents(List<Student> students) {
		this.students = students;
	}

	public int getClassId() {
		return classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Override
	public String toString() {
		return "V_Class [classId=" + classId + ", className=" + className + "]";
	}

}
